name: Deploy Tech Radar

on:
  push:
    branches:
      - master  # Run the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set Up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Use a compatible Node.js version

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Tech Radar
      - name: Build Tech Radar
        run: npx aoe_technology_radar build

      # Step 5: Move Build Files to Docs Directory
      - name: Move build files to docs folder
        run: |
          rm -rf docs
          mv .techradar docs

      # Step 6: Configure Deployment to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
